# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

#services:
#    pictura_controller:
#        class: AppBundle\Controller\PicturaController
#       arguments: ['%kernel.root_dir%']
